name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Build and Test
        run: xcodebuild -scheme "RickAndMorty12" -configuration Release clean build test -destination "platform=iOS Simulator,name=iPhone 15,OS=latest"
        env:
          DEVELOPER_DIR: /Applications/Xcode_16.app/Contents/Developer
