name: Xcode Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: macos-latest

    env:
      DEVELOPER_DIR: /Applications/Xcode_16.app/Contents/Developer
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Convert project format
      run: xcrun xcodebuild -project RickAndMorty.xcodeproj -updateToCheckout
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Build the project
      run: xcodebuild build -project RickAndMorty.xcodeproj -scheme YourScheme -destination 'platform=iOS Simulator,name=iPhone 15'
      
    - name: Run tests
      run: xcodebuild test -project RickAndMorty.xcodeproj -scheme YourScheme -destination 'platform=iOS Simulator,name=iPhone 15'
